### PR TITLE
Added "less / greater than" comparison tests

### PR DESCRIPTION
**Pull request by Dommar92**
New Asserts:
TEST_ASSERT_GREATER_THAN_INT(shouldBeGreater, actual)
Success, if shouldBeGreater > actual, fails otherwise.

TEST_ASSERT_LESS_THAN_INT(shouldBeSmaller, actual)
Success, if shouldBeSmaller < actual, fails otherwise.

Needed this in a project, so I added it. May be useful to others.

### CODE REVIEW

**Comment by art-of-dom** [comment]
While I like this change a lot, can you revert all the spacing/style changes in unity.c so it doesn't change as much. This will cause conflicts with forked and branched changes trying to merge back in as your changes are so big.

**Comment by Dommar92** [comment]
Yes, you are right. Sorry for that! Will do it tomorrow!

**Comment by mvandervoord** [comment]
If anyone would like to clean up this PR, I'd still be interested in merging it.

**Comment by mvandervoord** [comment]
Merged the cleaner #285. Thanks for the work, everyone!

**Pull request closed without merging**
