### PR TITLE
Fix undefined behavior in UnityPrintNumber

### PR DESCRIPTION
**Pull request by jlindgren90**
And add sanitizers to the GCC build flags so that no-one breaks this again.

### CODE REVIEW

**Comment by jlindgren90** [comment]
Is there any particular reason your CI builds are still on GCC 4.8?

**Comment by mvandervoord** [comment]
Awesome. Thank you. 

I must apologize, I just committed the latter portion, but I like yours with the comment. Can you merge master and update the PR?

**Comment by mvandervoord** [comment]
Yes. To catch problems like the one you just committed. :)

I've been meaning to add additional versions so that I can run tests with cutting edge AND older versions... but haven't been able to thus far.

**Comment by jlindgren90** [comment]
You don't need anything cutting-edge to run sanitizers.  GCC 4.9.0 (5+ years old) or even older versions of clang would do it.

I'll close this.  Feel free to copy the comment if you like.

**Comment by mvandervoord** [comment]
4.9 sounds like a winner, then! Thanks for the advice!

**Pull request closed without merging**
