### PR TITLE
Convert PDF docs to markdown

### PR DESCRIPTION
**Pull request by wolf99**
This is in aid of #273 as [requested](https://github.com/ThrowTheSwitch/Unity/issues/273#issuecomment-289619879)

Note that the conversion is direct as I could make it, thus errors in the source PDFs, such as broken or incorrectly formatted links, remain in the markdown version (mainly because I wasn't sure what to replace them with, so maybe they should constitute a new issue).

### CODE REVIEW

**Comment by wolf99** [comment]
Not sure why the deletion of this particular PDF is causing a conflict? All PDFs that were deleted were deleted together and committed in a single commit. and my branch is currently from master where master is at its most recent.

**Comment by mvandervoord** [comment]
I made a change to the AssertionsReference to add documentation for the new array alternatives TEST_ASSERT_EACH_EQUAL_INT and friends. It appears from the document that you generated, that your source was from before these changes were inserted. I suspect this is why there is a conflict. 

We can go with your version and then I'll just re-add those details. :)

**Comment by wolf99** [comment]
Almost forgot to note that the markdown uses _Github-flavoured_ markdown rather than regular markdown. In a lot of cases this will not matter but some strict renderers may barf some things in it, such as the code blocks that use the three-back-tick fences, for example.

**Comment by wolf99** [comment]
Ah, I see I pulled and rebased on _my_ remote, rather than the ThrowTheSwitch remote, D'oh! Ill rebase properly now

**Comment by wolf99** [comment]
the branch is now rebased correctly and I have added the EACH_EQUAL changes 😃

**Pull request merged**
