### PR TITLE
[Feature] Range Testing TEST_CASE()-like macro

### PR DESCRIPTION
**Pull request by alejmrm**
Sometimes I want to sweep a function under test with a range of values that stress it. Initially, I start by adding a TEST_CASE() macro before the test as described in the documentation and works fine, but overtime I am ending up with several TEST_CASE() macros. What I am proposing is that TEST_CASE-like macro takes a range of values that are passed to the test function.

``` C
TEST_RANGE( [ 11, 20, 1 ], [ 0.0, 5.0, 0.5] );
void test_foo(int a, float b)
{
   /* your standard test goes here */
};
```

Where the TEST_RANGE() macro will take the following entries per array item:
arg1 => start range
arg2 => stop range
arg3 => the increment unit

So the following example:

``` C
TEST_RANGE( [ 1, 3, 1 ], [ 0.0, 2.0, 1.0] );
```

Will create two nested loops, the top loop start with a value equal to 1 and increments by 1 until reach 3, while the inner loop starts with a value of 0.0 and increments by 1.0 until reach 2.0.

The declaration is similar as TEST_CASE(), for example:

``` C
#define  TEST_RANGE(...)
```

Translated the above example into sudo-ruby, we get:

``` Ruby
range_int = 0
while range_int <= 3  do # 1st argument
    range_float = 0.0
    while range_float <= 2.0 do # 2nd argument
         output.puts("RUN_TEST( test_foo, line_number, range_int, range_float );")
         range_float += 1.0
    end
    range_int += 1
end
```

In the runner we will end-up with the following familiar structure:

``` C
    ...
    RUN_TEST( test_foo, range_int, <line_number>, 0, 0.0 )
    RUN_TEST( test_foo, range_int, <line_number>, 0, 1.0 )
    RUN_TEST( test_foo, range_int, <line_number>, 0, 2.0 )
    RUN_TEST( test_foo, range_int, <line_number>, 1, 0.0 )
    RUN_TEST( test_foo, range_int, <line_number>, 1, 1.0 )
    RUN_TEST( test_foo, range_int, <line_number>, 1, 2.0 )
    RUN_TEST( test_foo, range_int, <line_number>, 2, 0.0 )
    RUN_TEST( test_foo, range_int, <line_number>, 2, 1.0 )
    RUN_TEST( test_foo, range_int, <line_number>, 2, 2.0 )
    RUN_TEST( test_foo, range_int, <line_number>, 3, 0.0 )
    RUN_TEST( test_foo, range_int, <line_number>, 3, 1.0 )
    RUN_TEST( test_foo, range_int, <line_number>, 3, 2.0 )
    ...
```

### CODE REVIEW

**Comment by Letme** [comment]
Any ideas why this got left behind? Can I help with something to get it up to speed?

**Comment by yanma** [comment]
I guess this pull-request is not merged because it has complex conflicts.
I extracted essential codes from the commits and re-implemented them.

https://github.com/yanma/Unity/commit/a3e398a1cde9b7fc3d03f7835acc8e0066735bd0

- It can work with my several sample codes.
- It can be merged into the latest master without conflict.
- In addition to original commit, it allows multiple TEST_RANGEs and TEST_CASE/TEST_RANGE mixture.

Could anyone review my code and let me know if it is acceptable?
If yes, I'll open another pull-request with my commit above.
Thank you.

**Comment by alejmrm** [comment]
Letme, I don't know the project owner didn't include this change request, probably I didn't explain the feature properly. Anyway, by now, I will need to re-implement it due the baseline is really really old.

yanma, thank you for bringing this feature up to date. I will say that you should create a request for this from your branch. but please let me know it so I can cancel this pull request.

thank you, Alex.

**Comment by yanma** [comment]
@alejmrm Thank you for your comment.
Sure! I think you are the best person to check my code because I just refactored your code.
I refactored my code again. Please check the difference below.
https://github.com/yanma/Unity/compare/master...yanma:feature_test_range_again

The parametrized test consists of two parts as below.
- Find and parse the test macros described in test code.
- Create the RUN_TEST macro from the parsed result.

Currently they are hard coded in the script.
I separated them as below.

- Find section
-- find_test_for_normal_case
-- find_test_for_range_case
- Create section
-- create_tagged_testcase
-- create_tagged_testrange

They can be defined multipully.
Here is the examples.

// Generate test case for 0
TEST_CASE(0)
// Generate test case for 4, 6, 8, 10
TEST_RANGE([4, 10, 2])
// Generate test case for 11, 12, 13, 14
TEST_RANGE([11, 14, 1])
void test_sample(int Num)
{
	// test and assertion
}

This generates test case of Num = 0, 4, 6, 8, 10, 11, 12, 13, 14 for test_sample.
If you have any questions, please let me know.

Thank you!

**Comment by Letme** [comment]
Maybe for trace-ability this would be better to move current merge request to yanma branch if possible or merge changes from yanma branch into alex-es, so that we have them here.

**Comment by yanma** [comment]
@alejmrm Hello. What can I do to accelerate this discussion? If you need further explanation, please feel free to ask me. Thank you.

**Comment by yanma** [comment]
I fixed generate_test_runner.rb so that it can find no macro case. https://github.com/yanma/Unity/commit/e459406609a68e9688f1f4a2b87a520ad2b8bd11

**Pull request closed without merging**
