### PR TITLE
Adding test matrix feature

### PR DESCRIPTION
**Pull request by AJIOB**
As an analog for `TEST_CASE(...)` & `TEST_RANGE(...)`, you can use `TEST_MATRIX(...)` for defining custom test cases.

`TEST_MATRIX` macro parsing can be enabled together with `TEST_RANGE`.

Supports almost all found C & C++ literals & expressions (expect array addressing with `[]`, such as `my_arr[26]`). Also supports multiline matrixes, ranges & cases.

Examples of some tests with that usage:
```c
TEST_MATRIX([ "World", "More \"words", "than ]", "one)", NULL ], [ 5, 8, 4, 32 ])
TEST_MATRIX([
        NULL, "name",
        "name1", "2name", "33name"
    ], [4])
void test_nothing(const char *s, uint32_t b)
{
    TEST_ASSERT_NOT_NULL_MESSAGE(s, "Bad string");
    TEST_ASSERT_NOT_EQUAL_UINT32_MESSAGE(0, b, "Number is zero");
}
```

### CODE REVIEW

**Comment by AJIOB** [comment]
Hello @mvandervoord,

Have I lost some requirements for merging that merge?

With regards,
Alex

**Comment by mvandervoord** [comment]
Hi Alex:

I'm trying to figure out a good way to test all of this. It's going to require tests to make sure the script itself performs the job assigned, as well as that both the code using the new notation and the generated code both actually perform their job and compile without error. 

Also, we're going to want to make sure the documentation for the new feature gets added.

These things don't all have to be on you, necessarily, but they're important for a significant feature like this.

**Comment by AJIOB** [comment]
Hi Mark

As you can see, Unity-generated outputs will generate correct XML files. If you pass the `-suiteHelloWorld` flag, the default `Unity` test suite name will be replaced with `HelloWorld` in XML output.

File with 2 different outputs in 4 different forms (with/without color & with/without time) is available [here](https://github.com/ThrowTheSwitch/Unity/files/8153513/UnityDifferentOutputs.zip).

With regards,
Alex

**Comment by jonhenneberg** [comment]
@AJIOB and @mvandervoord Was this abandoned for some other/better solution ?

I'm interested in the feature, and was considering adding something to our local fork of Unity, but would rather add it to the upstream project, so if it wasn't dropped due to some other design or an incompatibility, I was contemplating brushing this PR off, getting it updated and looking at what could be done to add tests to it.

**Comment by mvandervoord** [comment]
I just haven't had time to get back on this, unfortunately. :(

**Comment by mvandervoord** [comment]
@jonhenneberg -- it would not be a wasted effort. In fact, it would be much appreciated. :)

**Pull request closed without merging**
