### PR TITLE
TI C55x compatibility

### PR DESCRIPTION
**Pull request by detly**
This includes some of the minor fixes from PR #393 that didn't make it in (tweaked a bit as per discussion):

> Here are some smaller changes that help getting Unity to work more fully on some of TI's DSP platforms. Specifically:

- Relaxed the pointer width restrictions. A few DSPs have weird pointer widths like 23/24 bits (or eg. 15, or 31, due to the top bit being reserved for special "kinds" of addressing). There's no reason you can't cast a 23-bit pointer into a 32-bit int and print that, so I relaxed the restrictions on this.

- Check `CHAR_BIT`. If it's not exactly 8 (remember, the standard says it must be *at least* 8), there's now an extra macro `UNITY_NO_SUPPORT_8` defined that allows for ignoring tests that rely on strictly-8-bit behavious

- TI's clxx compilers are nominally C89 compilers, but support a bunch of C99 features such as variadic macros. This is actually a common thing in embedded toolchains. So I added a macro and supporting docs to tell Unity to use the variadic macro version of `RUN_TEST()` even on a claims-to-be-C89 toolchain.

Issues I couldn't fix due to incompatibility with PR #403 :

- #420 
- #421 

Other related issues that aren't really that critical:

- #418 
- #417

### CODE REVIEW

**Comment by farrrb** [comment]
I'm not sure about the relaxed pointer widths anymore. Maybe unity should auto-detect the width and adjust the value to the next power of 2 in order to do arithmetic on the widths. It is nearly impossible to derive a type in which the pointer fits based on an arbitrary pointer width given (23 for example). 

I think it would be wise to differentiate between the system's pointer width and unity's pointer width (like UNITY_INT which is always 32 or 64 bit but never 16 bits wide).

See #420 for more information.

**Comment by detly** [comment]
Entirely possible, but I guess my problem with that is — what's the point
in calculating an arbitrary power of two if various other parts of Unity
assume 32 or 64 only?

**Comment by detly** [comment]
(Also how would it auto-detect the pointer width in bits? We can't even rely on auto-detecting a `char` width in bits without introducing a dependency on `limits.h`.)

**Comment by farrrb** [comment]
The mechanism for unity is a little bit complicated but it works very well on many platforms.
There are three stages:
1. check limits.h for types and determine the integer (UINT_MAX) & long (ULONG_MAX) type
2. check stdint.h (UINTPTR_MAX) for types and determine the pointer type (with using the next power of two)
If this doesn't work (in case there is no limits.h and/or nor stdint.h):
3. fallback to default (UNITY_INT = 32-bit, UNITY_LONG_WIDTH = 32-bit and UNITY_POINTER_WIDTH = 32-bit). 

This mechanism can be overriden by manual definition of these macros. But you have to keep in mind that you should only set power-of-two values, because the slightly smaller types will be handled like them (which is totally fine in my opinion). 
One should always try to autodetect your processor first. Only if this doesn't work one should set the macros manually. 

The TI C55x should be autodetected with a 16-bit int type, a 32-bit long type and a 32-bit pointer type as I can infer from the limits.h and stdint.h of the C55x standard library. Imho the documentation should be updated to make this more clear.

**Comment by mvandervoord** [comment]
Replaced by #425

**Pull request closed without merging**
