### PR TITLE
auto: Only create run_test() function if it's needed.

### PR DESCRIPTION
**Pull request by jlindgren90**
Also fix some whitespace consistency issues.
Use 2 newlines (not 1 or 3) before /*====Heading====*/ comments.

### CODE REVIEW

**Comment by mvandervoord** [comment]
I'm not quite following why you would want to run the test runner generator and have it not produce run_test?

**Comment by jlindgren90** [comment]
It happens in code that is tested with multiple build options.  Sometimes all of the tests in a particular file are preprocessed out under a particular build option.

**Comment by mvandervoord** [comment]
And when that happens, was it producing an error? What are we avoiding by removing the function?

**Comment by jlindgren90** [comment]
Not an error, but a warning about an unused static function.  It seemed reasonable to fix the warning at the cost of adding three words ("unless tests.empty?")

**Pull request merged**
