### PR TITLE
Adding within API support for float & double arrays

### PR DESCRIPTION
**Pull request by AJIOB**
* Implementing feature requests #630 & #574
* Fixing copy-paste bug with UnityFloatsWithin usage instead of UnityDoublesWithin
* Adding lost entries for exclusion (float & double)

### CODE REVIEW

**Comment by Letme** [comment]
We already have a bit more hardcoded delta with `UNITY_FLOAT_PRECISION`. So instead of changing functions `UnityFloatsWithin` and `UnityDoublesWithin` just change the calls of those functions within a macro to have the delta user defined.

**Comment by AJIOB** [comment]
@Letme If I correctly understand you, implementation was fixed, as you want.

**Comment by Letme** [comment]
yes, I think it makes more sense. I like the solution. :+1:

**Comment by pr0g** [comment]
I just wanted to +1 this change as it looks super useful. Is there an ETA on when it might be merged?

I've been using Unity for testing a noddy little math library written in C and this change would allow me to simplify a number of tests quite a bit.

Thanks!

**Comment by AJIOB** [comment]
@mvandervoord @pr0g 
IMHO, all code is ready to merge.

**Comment by pr0g** [comment]
Hmm maybe @mkarlesky, @mvandervoord or @barneywilliams could merge? Or anyone else with merge/review privileges?

**Comment by pr0g** [comment]
Or @Letme if the code updates have been verified and are accepted?

**Comment by AJIOB** [comment]
@mvandervoord 
Hello Mark,

What I need to fix for merging that PR/changes?

With regards,
Alex

**Comment by CezaryGapinski** [comment]
@mvandervoord  Any chances to merge this PR?

**Comment by pr0g** [comment]
Maybe @AJIOB could rebase the PR so it's not behind the latest changes in `master` and people can then use that fork and commit as the version to use? Until it can be merged that is (I'm using the library with FetchContent so I might just update the repo/commit when I download/build the dependency - or make my own fork with the patch applied if needed)

**Comment by hultonha** [comment]
Awesome! Thanks @mvandervoord! 🥳

**Comment by pr0g** [comment]
Awesome thank you @mvandervoord! 🥳

**Comment by mvandervoord** [comment]
Thanks to @AJIOB for these improvements. My apologies it's been taking me so long to keep up with these things recently.

**Comment by pr0g** [comment]
I've already put this to good use in my little C math library experiment.

You can see the changes here: https://github.com/pr0g/as-c-math/commit/1264bdfccd914f66e152f5328cb1dc15bd1338bf#diff-053c8553fc41cf01946042b7703174567d1d7ce966be033df3d585f9dff9d9b4

The change saved 327 lines and is much cleaner to read. So much nicer already 😁

Great work @AJIOB and thanks again for merging @mvandervoord.

**Pull request merged**
