### PR TITLE
Update generate test runner to leverage custom UNITY_END()

### PR DESCRIPTION
**Pull request by andre-lei**
Hi, I am looking to leverage a custom UNITY_END() and still use the test runner generator script.
- Changed reference in `generate_test_runner.rb` from `UnityEnd()` -> `UNITY_END()`

Thanks

### CODE REVIEW

**Comment by andre-lei** [comment]
Marking this as draft for now, place let me know if this is an acceptable change.

**Comment by mvandervoord** [comment]
@andre-lei -- this change makes a lot of sense to me. Honestly, I'm embarrassed it isn't this way already. It's clearly a better solution..

**Comment by andre-lei** [comment]
Hi @mvandervoord, curious if there are additional changes required before we can merge this change it ?
Thanks!

**Comment by mvandervoord** [comment]
Fixed

**Comment by andre-lei** [comment]
Hi @mvandervoord, seems like this wasn't merged in. Can this be reopened ?

**Pull request closed without merging**
